"""
CLI 自动补全脚本生成 - Shell Completion Scripts

支持 Bash/Zsh/Fish 自动补全脚本生成
提供命令历史记录和交互式提示增强

作者: UFO Framework Team
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import List, Dict, Any, Optional, Callable
from dataclasses import dataclass, field
from collections import defaultdict
import readline
import atexit


@dataclass
class CompletionConfig:
    """补全配置"""
    shell: str = "bash"  # bash, zsh, fish
    program_name: str = "ufo"
    history_file: str = ".ufo_history"
    history_size: int = 1000
    enable_fuzzy: bool = True
    case_sensitive: bool = False


class CommandRegistry:
    """
    命令注册表

    管理所有可用的CLI命令及其参数
    """

    def __init__(self):
        self.commands: Dict[str, Dict[str, Any]] = {}
        self.global_options: Dict[str, str] = {}

    def register_command(
        self,
        name: str,
        description: str,
        arguments: Optional[List[Dict]] = None,
        options: Optional[List[Dict]] = None,
        subcommands: Optional[List[str]] = None,
    ):
        """注册命令"""
        self.commands[name] = {
            "description": description,
            "arguments": arguments or [],
            "options": options or [],
            "subcommands": subcommands or [],
        }

    def register_global_option(self, name: str, description: str):
        """注册全局选项"""
        self.global_options[name] = description

    def get_all_commands(self) -> List[str]:
        """获取所有命令名称"""
        return list(self.commands.keys())

    def get_command_options(self, command: str) -> List[str]:
        """获取命令的选项"""
        if command in self.commands:
            return [opt.get("name", "") for opt in self.commands[command]["options"]]
        return []

    def get_command_subcommands(self, command: str) -> List[str]:
        """获取命令的子命令"""
        if command in self.commands:
            return self.commands[command]["subcommands"]
        return []


class BashCompletionGenerator:
    """Bash 补全脚本生成器"""

    def __init__(self, registry: CommandRegistry, program_name: str = "ufo"):
        self.registry = registry
        self.program_name = program_name

    def generate(self) -> str:
        """生成Bash补全脚本"""
        script = f'''#!/bin/bash
# Bash completion script for {self.program_name}
# Auto-generated by UFO CLI

_{self.program_name}_completions() {{
    local cur prev opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    # 全局选项
    local global_opts="{self._get_global_options()}"

    # 命令列表
    local commands="{self._get_commands()}"

    # 获取当前命令
    local cmd=""
    for ((i=1; i<${{COMP_CWORD}}; i++)); do
        if [[ " ${{commands}} " =~ " ${{COMP_WORDS[i]}} " ]]; then
            cmd="${{COMP_WORDS[i]}}"
            break
        fi
    done

    # 如果没有命令，补全命令
    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W "${{commands}} ${{global_opts}}" -- "$cur") )
        return 0
    fi

    # 根据命令补全
    case "$cmd" in
{self._get_case_statements()}
    esac
}}

complete -F _{self.program_name}_completions {self.program_name}
'''
        return script

    def _get_global_options(self) -> str:
        """获取全局选项字符串"""
        return " ".join(self.registry.global_options.keys())

    def _get_commands(self) -> str:
        """获取命令字符串"""
        return " ".join(self.registry.get_all_commands())

    def _get_case_statements(self) -> str:
        """生成case语句"""
        cases = []
        for cmd_name, cmd_info in self.registry.commands.items():
            opts = " ".join([opt.get("name", "") for opt in cmd_info["options"]])
            subcmds = " ".join(cmd_info["subcommands"])

            case_body = f'''        {cmd_name})
            local opts="{opts}"
            local subcmds="{subcmds}"
            if [[ "$prev" == "{cmd_name}" ]]; then
                COMPREPLY=( $(compgen -W "${{subcmds}} ${{opts}}" -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "${{opts}}" -- "$cur") )
            fi
            return 0
            ;;'''
            cases.append(case_body)

        return "\n".join(cases)


class ZshCompletionGenerator:
    """Zsh 补全脚本生成器"""

    def __init__(self, registry: CommandRegistry, program_name: str = "ufo"):
        self.registry = registry
        self.program_name = program_name

    def generate(self) -> str:
        """生成Zsh补全脚本"""
        script = f'''#compdef {self.program_name}
# Zsh completion script for {self.program_name}
# Auto-generated by UFO CLI

_{self.program_name}() {{
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \\
        {self._get_global_arguments()} \\
        '1: :->command' \\
        '*:: :->args'

    case "$state" in
        command)
            local commands=(
{self._get_command_descriptions()}
            )
            _describe -t commands 'command' commands
            ;;
        args)
            case "$line[1]" in
{self._get_subcommand_handlers()}
            esac
            ;;
    esac
}}

_{self.program_name} "$@"
'''
        return script

    def _get_global_arguments(self) -> str:
        """获取全局参数定义"""
        args = []
        for opt, desc in self.registry.global_options.items():
            if opt.startswith("--"):
                short = opt.replace("--", "-")[0] if len(opt) > 2 else ""
                args.append(f"'{opt}[{desc}]'")
        return " \\\n        ".join(args)

    def _get_command_descriptions(self) -> str:
        """获取命令描述"""
        descriptions = []
        for cmd_name, cmd_info in self.registry.commands.items():
            desc = cmd_info["description"].replace("'", "\\'")
            descriptions.append(f'                "{cmd_name}:{desc}"')
        return "\n".join(descriptions)

    def _get_subcommand_handlers(self) -> str:
        """获取子命令处理器"""
        handlers = []
        for cmd_name, cmd_info in self.registry.commands.items():
            opts = []
            for opt in cmd_info["options"]:
                opt_name = opt.get("name", "")
                opt_desc = opt.get("description", "").replace("'", "\\'")
                if opt_name.startswith("--"):
                    opts.append(f"'{opt_name}[{opt_desc}]'")

            handler = f'''                {cmd_name})
                    _arguments \\
                        {' \\\n                        '.join(opts) if opts else "'*:file:_files'"}
                    ;;'''
            handlers.append(handler)

        return "\n".join(handlers)


class FishCompletionGenerator:
    """Fish 补全脚本生成器"""

    def __init__(self, registry: CommandRegistry, program_name: str = "ufo"):
        self.registry = registry
        self.program_name = program_name

    def generate(self) -> str:
        """生成Fish补全脚本"""
        lines = [
            f"# Fish completion script for {self.program_name}",
            f"# Auto-generated by UFO CLI",
            "",
        ]

        # 全局选项
        for opt, desc in self.registry.global_options.items():
            lines.append(f'complete -c {self.program_name} -l {opt.lstrip("-")} -d "{desc}"')

        lines.append("")

        # 命令
        for cmd_name, cmd_info in self.registry.commands.items():
            lines.append(f'complete -c {self.program_name} -f -n "__fish_use_subcommand" -a {cmd_name} -d "{cmd_info["description"]}"')

            # 命令选项
            for opt in cmd_info["options"]:
                opt_name = opt.get("name", "").lstrip("-")
                opt_desc = opt.get("description", "")
                lines.append(f'complete -c {self.program_name} -n "__fish_seen_subcommand_from {cmd_name}" -l {opt_name} -d "{opt_desc}"')

            # 子命令
            for subcmd in cmd_info["subcommands"]:
                lines.append(f'complete -c {self.program_name} -n "__fish_seen_subcommand_from {cmd_name}" -a {subcmd}')

        return "\n".join(lines)


class CommandHistory:
    """
    命令历史记录管理

    提供命令历史记录、搜索和自动补全功能
    """

    def __init__(self, history_file: str = ".ufo_history", max_size: int = 1000):
        self.history_file = Path.home() / history_file
        self.max_size = max_size
        self.history: List[str] = []
        self.command_frequency: Dict[str, int] = defaultdict(int)

        self._load_history()
        self._setup_readline()

    def _load_history(self):
        """加载历史记录"""
        if self.history_file.exists():
            try:
                with open(self.history_file, 'r', encoding='utf-8') as f:
                    self.history = [line.strip() for line in f if line.strip()]
                    for cmd in self.history:
                        self.command_frequency[cmd] += 1
            except Exception as e:
                print(f"Warning: Could not load history: {e}")

    def _save_history(self):
        """保存历史记录"""
        try:
            with open(self.history_file, 'w', encoding='utf-8') as f:
                for cmd in self.history[-self.max_size:]:
                    f.write(f"{cmd}\n")
        except Exception as e:
            print(f"Warning: Could not save history: {e}")

    def _setup_readline(self):
        """设置readline"""
        # 设置历史文件
        readline.parse_and_bind('tab: complete')

        # 设置补全函数
        readline.set_completer(self._completer)

        # 注册退出时保存
        atexit.register(self._save_history)

    def _completer(self, text: str, state: int) -> Optional[str]:
        """readline补全函数"""
        matches = [cmd for cmd in self.history if cmd.startswith(text)]
        matches = list(dict.fromkeys(matches))  # 去重

        if state < len(matches):
            return matches[state]
        return None

    def add_command(self, command: str):
        """添加命令到历史"""
        if command.strip():
            self.history.append(command.strip())
            self.command_frequency[command.strip()] += 1

            # 限制历史大小
            if len(self.history) > self.max_size:
                self.history = self.history[-self.max_size:]

    def get_recent_commands(self, n: int = 10) -> List[str]:
        """获取最近的命令"""
        return self.history[-n:]

    def get_frequent_commands(self, n: int = 10) -> List[str]:
        """获取最频繁的命令"""
        sorted_cmds = sorted(
            self.command_frequency.items(),
            key=lambda x: x[1],
            reverse=True
        )
        return [cmd for cmd, _ in sorted_cmds[:n]]

    def search_history(self, pattern: str) -> List[str]:
        """搜索历史记录"""
        import re
        try:
            regex = re.compile(pattern, re.IGNORECASE)
            return [cmd for cmd in self.history if regex.search(cmd)]
        except re.error:
            return [cmd for cmd in self.history if pattern.lower() in cmd.lower()]

    def clear_history(self):
        """清空历史记录"""
        self.history.clear()
        self.command_frequency.clear()
        self._save_history()


class InteractivePrompt:
    """
    交互式提示增强

    提供智能提示、语法高亮、多行编辑等功能
    """

    def __init__(self, registry: CommandRegistry, history: CommandHistory):
        self.registry = registry
        self.history = history
        self.suggestions: List[str] = []
        self.current_suggestion_index = 0

    def get_prompt(self) -> str:
        """获取提示符"""
        return "ufo> "

    def suggest_command(self, partial: str) -> List[str]:
        """建议命令"""
        suggestions = []

        # 匹配命令
        for cmd in self.registry.get_all_commands():
            if cmd.startswith(partial):
                suggestions.append(cmd)

        # 匹配历史
        for cmd in self.history.get_recent_commands():
            if cmd.startswith(partial) and cmd not in suggestions:
                suggestions.append(cmd)

        return suggestions

    def suggest_options(self, command: str, partial: str) -> List[str]:
        """建议选项"""
        options = self.registry.get_command_options(command)
        return [opt for opt in options if opt.startswith(partial)]

    def format_help(self, command: Optional[str] = None) -> str:
        """格式化帮助信息"""
        if command and command in self.registry.commands:
            cmd_info = self.registry.commands[command]
            lines = [
                f"Command: {command}",
                f"Description: {cmd_info['description']}",
                "",
                "Options:",
            ]
            for opt in cmd_info["options"]:
                lines.append(f"  {opt.get('name', '')} - {opt.get('description', '')}")

            if cmd_info["subcommands"]:
                lines.append("")
                lines.append("Subcommands:")
                for sub in cmd_info["subcommands"]:
                    lines.append(f"  {sub}")

            return "\n".join(lines)
        else:
            lines = ["Available commands:"]
            for cmd_name, cmd_info in self.registry.commands.items():
                lines.append(f"  {cmd_name:20} - {cmd_info['description']}")
            return "\n".join(lines)

    def highlight_syntax(self, command_line: str) -> str:
        """语法高亮（简化版）"""
        # 实际实现可以使用rich或prompt_toolkit
        return command_line


class CompletionManager:
    """
    补全管理器

    统一管理所有补全相关功能
    """

    def __init__(self, program_name: str = "ufo"):
        self.program_name = program_name
        self.registry = CommandRegistry()
        self.history = CommandHistory()
        self.prompt = InteractivePrompt(self.registry, self.history)

        self._register_default_commands()

    def _register_default_commands(self):
        """注册默认命令"""
        # 全局选项
        self.registry.register_global_option("--help", "Show help message")
        self.registry.register_global_option("--version", "Show version")
        self.registry.register_global_option("--verbose", "Enable verbose output")
        self.registry.register_global_option("--config", "Specify config file")

        # 命令
        self.registry.register_command(
            "train",
            "Train a model",
            options=[
                {"name": "--model", "description": "Model name or path"},
                {"name": "--data", "description": "Training data path"},
                {"name": "--epochs", "description": "Number of epochs"},
                {"name": "--batch-size", "description": "Batch size"},
                {"name": "--lr", "description": "Learning rate"},
            ],
        )

        self.registry.register_command(
            "inference",
            "Run inference",
            options=[
                {"name": "--model", "description": "Model name or path"},
                {"name": "--input", "description": "Input text or file"},
                {"name": "--output", "description": "Output file"},
                {"name": "--max-tokens", "description": "Maximum tokens to generate"},
            ],
        )

        self.registry.register_command(
            "config",
            "Manage configuration",
            subcommands=["get", "set", "list", "reset"],
            options=[
                {"name": "--global", "description": "Use global config"},
            ],
        )

        self.registry.register_command(
            "completion",
            "Generate shell completion scripts",
            subcommands=["bash", "zsh", "fish"],
            options=[
                {"name": "--output", "description": "Output file path"},
            ],
        )

    def generate_completion_script(self, shell: str, output_path: Optional[str] = None) -> str:
        """
        生成补全脚本

        Args:
            shell: shell类型 (bash, zsh, fish)
            output_path: 输出文件路径

        Returns:
            补全脚本内容
        """
        if shell == "bash":
            generator = BashCompletionGenerator(self.registry, self.program_name)
        elif shell == "zsh":
            generator = ZshCompletionGenerator(self.registry, self.program_name)
        elif shell == "fish":
            generator = FishCompletionGenerator(self.registry, self.program_name)
        else:
            raise ValueError(f"Unsupported shell: {shell}")

        script = generator.generate()

        if output_path:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(script)
            os.chmod(output_path, 0o755)
            print(f"Completion script saved to: {output_path}")

        return script

    def install_completion(self, shell: str):
        """安装补全脚本"""
        import platform

        if shell == "bash":
            completion_dir = Path.home() / ".bash_completion.d"
            completion_dir.mkdir(exist_ok=True)
            output_path = completion_dir / f"{self.program_name}"
            self.generate_completion_script("bash", str(output_path))

            # 添加到.bashrc
            bashrc = Path.home() / ".bashrc"
            source_line = f'[ -f "{output_path}" ] && source "{output_path}"'

            with open(bashrc, 'r', encoding='utf-8') as f:
                content = f.read()

            if source_line not in content:
                with open(bashrc, 'a', encoding='utf-8') as f:
                    f.write(f"\n# UFO CLI completion\n{source_line}\n")

            print(f"Bash completion installed. Run 'source ~/.bashrc' to activate.")

        elif shell == "zsh":
            completion_dir = Path.home() / ".zsh" / "completions"
            completion_dir.mkdir(parents=True, exist_ok=True)
            output_path = completion_dir / f"_{self.program_name}"
            self.generate_completion_script("zsh", str(output_path))

            print(f"Zsh completion installed to: {output_path}")
            print("Make sure ~/.zsh/completions is in your $fpath")

        elif shell == "fish":
            completion_dir = Path.home() / ".config" / "fish" / "completions"
            completion_dir.mkdir(parents=True, exist_ok=True)
            output_path = completion_dir / f"{self.program_name}.fish"
            self.generate_completion_script("fish", str(output_path))

            print(f"Fish completion installed to: {output_path}")

    def get_history(self) -> CommandHistory:
        """获取历史记录管理器"""
        return self.history

    def get_prompt(self) -> InteractivePrompt:
        """获取交互式提示"""
        return self.prompt


def main():
    """主函数 - 用于测试"""
    manager = CompletionManager()

    print("=" * 60)
    print("CLI Completion Manager")
    print("=" * 60)

    # 生成各种shell的补全脚本
    for shell in ["bash", "zsh", "fish"]:
        print(f"\n[{shell.upper()}]")
        script = manager.generate_completion_script(shell)
        print(f"Generated {len(script)} characters")

    # 显示帮助
    print("\n[Help]")
    print(manager.prompt.format_help())

    # 显示历史
    print("\n[History]")
    print(f"Recent commands: {manager.history.get_recent_commands(5)}")


if __name__ == "__main__":
    main()
