"""
AISEC Tool Firewall Module
===========================
AEGIS three-stage firewall, parameter extraction, risk scanning,
policy validation, and capability token management.
"""

from .aegis import (
    AEGISFirewall,
    PreChecker,
    RuntimeMonitor,
    PostAuditor,
    ToolCapabilityRegistry,
    RiskScorer,
    BlockDecision,
    FirewallPolicy,
)
from .param_extractor import (
    ParamExtractor,
    ASTParser,
    NestedResolver,
    TemplateExpander,
    TypeInferrer,
    SanitizationMarker,
    ExtractedParams,
)
from .risk_scanner import (
    RiskScanner,
    CommandInjectionDetector,
    PathTraversalDetector,
    SQLInjectionDetector,
    XSSDetector,
    SSRFDetector,
    DeserializationDetector,
    RiskReport,
)
from .policy import (
    PolicyEngine,
    PathPolicy,
    DomainPolicy,
    CommandPolicy,
    ResourceQuota,
    TimePolicy,
    RBACPolicy,
    PolicyEvaluator,
    PolicyDecision,
)
from .capability_token import (
    CapabilityToken,
    TokenGenerator,
    TokenValidator,
    TokenRevoker,
    CapabilityScope,
    DelegationChain,
    TokenIntrospector,
    TokenStore,
)

__all__ = [
    "AEGISFirewall",
    "PreChecker",
    "RuntimeMonitor",
    "PostAuditor",
    "ToolCapabilityRegistry",
    "RiskScorer",
    "BlockDecision",
    "FirewallPolicy",
    "ParamExtractor",
    "ASTParser",
    "NestedResolver",
    "TemplateExpander",
    "TypeInferrer",
    "SanitizationMarker",
    "ExtractedParams",
    "RiskScanner",
    "CommandInjectionDetector",
    "PathTraversalDetector",
    "SQLInjectionDetector",
    "XSSDetector",
    "SSRFDetector",
    "DeserializationDetector",
    "RiskReport",
    "PolicyEngine",
    "PathPolicy",
    "DomainPolicy",
    "CommandPolicy",
    "ResourceQuota",
    "TimePolicy",
    "RBACPolicy",
    "PolicyEvaluator",
    "PolicyDecision",
    "CapabilityToken",
    "TokenGenerator",
    "TokenValidator",
    "TokenRevoker",
    "CapabilityScope",
    "DelegationChain",
    "TokenIntrospector",
    "TokenStore",
]
