"""
Draft model management for speculative decoding.

This module provides:
- Draft model loading and initialization
- Candidate token generation
- Model switching between draft and target models
- Acceptance/rejection logic for speculative tokens
- Configuration for speculative decoding

Author: AGI Unified Framework Team
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple, Union
import time


class ModelRole(Enum):
    """Role of model in speculative decoding."""
    TARGET = "target"
    DRAFT = "draft"


class AcceptanceStrategy(Enum):
    """Strategy for accepting/rejecting draft tokens."""
    EXACT_MATCH = "exact_match"
    PROBABILITY_THRESHOLD = "probability_threshold"
    ADAPTIVE = "adaptive"


@dataclass
class SpeculativeConfig:
    """
    Configuration for speculative decoding.
    
    Attributes:
        draft_model_name: Name/path of draft model
        target_model_name: Name/path of target model
        num_draft_tokens: Number of tokens to speculate
        acceptance_strategy: Strategy for token acceptance
        acceptance_threshold: Probability threshold for acceptance
        max_draft_length: Maximum length for draft sequences
        temperature: Sampling temperature
        top_p: Top-p sampling parameter
        use_adaptive_drafting: Whether to use adaptive draft length
        early_exit_on_reject: Stop speculation on first rejection
        enable_verification: Verify draft tokens against target
    """
    draft_model_name: str = "gpt2-small"
    target_model_name: str = "gpt2-medium"
    num_draft_tokens: int = 4
    acceptance_strategy: AcceptanceStrategy = AcceptanceStrategy.EXACT_MATCH
    acceptance_threshold: float = 0.8
    max_draft_length: int = 512
    temperature: float = 1.0
    top_p: float = 0.9
    use_adaptive_drafting: bool = True
    early_exit_on_reject: bool = True
    enable_verification: bool = True
    
    def __post_init__(self) -> None:
        """Validate configuration parameters."""
        if not 1 <= self.num_draft_tokens <= 20:
            raise ValueError("num_draft_tokens must be between 1 and 20")
        if not 0 <= self.acceptance_threshold <= 1:
            raise ValueError("acceptance_threshold must be between 0 and 1")
        if not 0 < self.temperature <= 2.0:
            raise ValueError("temperature must be between 0 and 2.0")
        if not 0 < self.top_p <= 1.0:
            raise ValueError("top_p must be between 0 and 1")


@dataclass
class CandidateToken:
    """
    A candidate token generated by draft model.
    
    Attributes:
        token_id: The token ID
        text: Text representation of token
        probability: Probability assigned by draft model
        log_probability: Log probability
        position: Position in the draft sequence
        rank: Rank among all candidates at this position
    """
    token_id: int
    text: str
    probability: float
    log_probability: float
    position: int
    rank: int = 0
    
    def __post_init__(self) -> None:
        """Ensure valid probability values."""
        self.probability = max(0.0, min(1.0, self.probability))
        self.log_probability = (
            0.0 if self.probability == 0
            else self.log_probability if self.log_probability != 0
            else -abs(self.log_probability)
        )


@dataclass
class CandidateSequence:
    """
    A sequence of candidate tokens from draft model.
    
    Attributes:
        tokens: List of candidate tokens
        total_probability: Product of all token probabilities
        average_probability: Average token probability
        length: Number of tokens in sequence
        is_complete: Whether sequence is complete
    """
    tokens: List[CandidateToken]
    total_probability: float = 0.0
    average_probability: float = 0.0
    length: int = 0
    is_complete: bool = True
    
    def __post_init__(self) -> None:
        """Calculate sequence statistics."""
        self.length = len(self.tokens)
        if self.tokens:
            self.total_probability = 1.0
            for token in self.tokens:
                self.total_probability *= token.probability
            self.average_probability = sum(
                t.probability for t in self.tokens
            ) / len(self.tokens)
    
    def get_token_ids(self) -> List[int]:
        """Get list of token IDs."""
        return [t.token_id for t in self.tokens]
    
    def get_text(self) -> str:
        """Get concatenated token text."""
        return "".join(t.text for t in self.tokens)


@dataclass
class AcceptanceResult:
    """
    Result of acceptance/rejection check.
    
    Attributes:
        accepted_tokens: List of accepted token IDs
        rejected_tokens: List of rejected token IDs
        rejection_position: Position of first rejection (-1 if none)
        accepted_length: Number of accepted tokens
        rejection_reason: Reason for rejection
        target_probabilities: Probabilities from target model
        acceptance_ratio: Ratio of accepted tokens
    """
    accepted_tokens: List[int]
    rejected_tokens: List[int]
    rejection_position: int
    accepted_length: int
    rejection_reason: str = ""
    target_probabilities: List[float] = field(default_factory=list)
    acceptance_ratio: float = 0.0
    
    def __post_init__(self) -> None:
        """Calculate acceptance ratio."""
        total = len(self.accepted_tokens) + len(self.rejected_tokens)
        if total > 0:
            self.acceptance_ratio = len(self.accepted_tokens) / total


@dataclass
class DraftModelStats:
    """Statistics for draft model performance."""
    total_speculations: int = 0
    total_accepted: int = 0
    total_rejected: int = 0
    avg_acceptance_ratio: float = 0.0
    avg_draft_length: float = 0.0
    speedup_ratio: float = 0.0
    last_updated: float = field(default_factory=time.time)


class DraftModel(ABC):
    """
    Abstract base class for draft models in speculative decoding.
    
    Draft models are typically smaller, faster models that generate
    candidate tokens which are then verified by the target model.
    """
    
    @abstractmethod
    def generate_candidates(
        self,
        prompt_tokens: List[int],
        num_candidates: int,
        temperature: float = 1.0,
        top_p: float = 0.9
    ) -> List[CandidateToken]:
        """
        Generate candidate tokens.
        
        Args:
            prompt_tokens: Input token IDs
            num_candidates: Number of candidates to generate
            temperature: Sampling temperature
            top_p: Top-p sampling parameter
        
        Returns:
            List of CandidateToken objects
        """
        pass
    
    @abstractmethod
    def get_token_probabilities(
        self,
        prompt_tokens: List[int],
        candidate_tokens: List[int]
    ) -> List[float]:
        """
        Get probabilities for candidate tokens.
        
        Args:
            prompt_tokens: Input token IDs
            candidate_tokens: Candidate token IDs
        
        Returns:
            List of probabilities for each candidate
        """
        pass
    
    @abstractmethod
    def get_vocab_size(self) -> int:
        """Get vocabulary size."""
        pass
    
    @abstractmethod
    def get_max_length(self) -> int:
        """Get maximum sequence length."""
        pass
    
    @abstractmethod
    def get_model_name(self) -> str:
        """Get model name."""
        pass


class CandidateGenerator:
    """
    Generates candidate tokens using draft model.
    
    Supports various generation strategies including:
    - Top-k sampling
    - Top-p (nucleus) sampling
    - Greedy selection
    - Beam search
    """
    
    def __init__(self, draft_model: DraftModel, config: SpeculativeConfig) -> None:
        """
        Initialize candidate generator.
        
        Args:
            draft_model: Draft model to use
            config: Speculative decoding configuration
        """
        self.draft_model = draft_model
        self.config = config
    
    def generate(
        self,
        prompt_tokens: List[int],
        num_tokens: Optional[int] = None
    ) -> CandidateSequence:
        """
        Generate a candidate sequence.
        
        Args:
            prompt_tokens: Input token IDs
            num_tokens: Number of tokens to generate
        
        Returns:
            CandidateSequence with generated tokens
        """
        num_tokens = num_tokens or self.config.num_draft_tokens
        
        all_candidates: List[CandidateToken] = []
        current_prompt = list(prompt_tokens)
        
        for position in range(num_tokens):
            # Generate candidates for next position
            candidates = self.draft_model.generate_candidates(
                current_prompt,
                num_candidates=10,  # Generate top 10 for ranking
                temperature=self.config.temperature,
                top_p=self.config.top_p,
            )
            
            if not candidates:
                break
            
            # Rank candidates by probability
            candidates.sort(key=lambda c: c.probability, reverse=True)
            
            # Select top candidate for this position
            top_candidate = candidates[0]
            top_candidate.position = position
            top_candidate.rank = 0
            
            all_candidates.append(top_candidate)
            current_prompt.append(top_candidate.token_id)
            
            # Early exit if model signals EOS
            if top_candidate.token_id == self._get_eos_token():
                break
        
        return CandidateSequence(tokens=all_candidates)
    
    def generate_multiple(
        self,
        prompt_tokens: List[int],
        num_sequences: int
    ) -> List[CandidateSequence]:
        """
        Generate multiple candidate sequences.
        
        Args:
            prompt_tokens: Input token IDs
            num_sequences: Number of sequences to generate
        
        Returns:
            List of CandidateSequence objects
        """
        sequences = []
        
        for _ in range(num_sequences):
            sequence = self.generate(prompt_tokens)
            sequences.append(sequence)
        
        # Sort by average probability
        sequences.sort(key=lambda s: s.average_probability, reverse=True)
        
        return sequences
    
    def _get_eos_token(self) -> int:
        """Get end-of-sequence token ID."""
        return 0  # Common EOS token
    
    def get_stats(self) -> Dict[str, Any]:
        """Get generator statistics."""
        return {
            "draft_model": self.draft_model.get_model_name(),
            "num_draft_tokens": self.config.num_draft_tokens,
            "temperature": self.config.temperature,
            "top_p": self.config.top_p,
        }


class AcceptanceChecker:
    """
    Checks acceptance of draft tokens against target model.
    
    Supports multiple acceptance strategies:
    - Exact match: Accept if draft matches target exactly
    - Probability threshold: Accept if draft prob > threshold
    - Adaptive: Adjust threshold based on confidence
    """
    
    def __init__(
        self,
        target_model: DraftModel,
        config: SpeculativeConfig
    ) -> None:
        """
        Initialize acceptance checker.
        
        Args:
            target_model: Target model for verification
            config: Speculative decoding configuration
        """
        self.target_model = target_model
        self.config = config
    
    def check(
        self,
        prompt_tokens: List[int],
        draft_sequence: CandidateSequence
    ) -> AcceptanceResult:
        """
        Check acceptance of draft sequence.
        
        Args:
            prompt_tokens: Input token IDs
            draft_sequence: Draft sequence to verify
        
        Returns:
            AcceptanceResult with acceptance details
        """
        strategy = self.config.acceptance_strategy
        
        if strategy == AcceptanceStrategy.EXACT_MATCH:
            return self._check_exact_match(prompt_tokens, draft_sequence)
        elif strategy == AcceptanceStrategy.PROBABILITY_THRESHOLD:
            return self._check_probability_threshold(prompt_tokens, draft_sequence)
        elif strategy == AcceptanceStrategy.ADAPTIVE:
            return self._check_adaptive(prompt_tokens, draft_sequence)
        else:
            return self._check_exact_match(prompt_tokens, draft_sequence)
    
    def _check_exact_match(
        self,
        prompt_tokens: List[int],
        draft_sequence: CandidateSequence
    ) -> AcceptanceResult:
        """Check using exact match strategy."""
        if not draft_sequence.tokens:
            return AcceptanceResult(
                accepted_tokens=[],
                rejected_tokens=[],
                rejection_position=-1,
                accepted_length=0,
                rejection_reason="Empty draft sequence",
            )
        
        accepted: List[int] = []
        rejected: List[int] = []
        target_probs: List[float] = []
        rejection_position = -1
        
        current_prompt = list(prompt_tokens)
        
        for i, draft_token in enumerate(draft_sequence.tokens):
            # Get target model's prediction
            target_candidates = self.target_model.generate_candidates(
                current_prompt,
                num_candidates=1,
                temperature=0.0,  # Deterministic for verification
                top_p=1.0,
            )
            
            if not target_candidates:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                break
            
            target_top = target_candidates[0]
            target_probs.append(target_top.probability)
            
            # Check exact match
            if draft_token.token_id == target_top.token_id:
                accepted.append(draft_token.token_id)
            else:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                if self.config.early_exit_on_reject:
                    break
            
            current_prompt.append(draft_token.token_id)
        
        return AcceptanceResult(
            accepted_tokens=accepted,
            rejected_tokens=rejected,
            rejection_position=rejection_position,
            accepted_length=len(accepted),
            target_probabilities=target_probs,
        )
    
    def _check_probability_threshold(
        self,
        prompt_tokens: List[int],
        draft_sequence: CandidateSequence
    ) -> AcceptanceResult:
        """Check using probability threshold strategy."""
        if not draft_sequence.tokens:
            return AcceptanceResult(
                accepted_tokens=[],
                rejected_tokens=[],
                rejection_position=-1,
                accepted_length=0,
            )
        
        accepted: List[int] = []
        rejected: List[int] = []
        target_probs: List[float] = []
        rejection_position = -1
        
        current_prompt = list(prompt_tokens)
        
        for i, draft_token in enumerate(draft_sequence.tokens):
            # Get target probabilities
            draft_probs = self.draft_model_get_probs(current_prompt, draft_token.token_id)
            target_candidates = self.target_model.generate_candidates(
                current_prompt,
                num_candidates=1,
                temperature=0.0,
                top_p=1.0,
            )
            
            if not target_candidates:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                break
            
            target_top = target_candidates[0]
            target_prob = target_top.probability
            target_probs.append(target_prob)
            
            # Check against threshold
            if target_prob >= self.config.acceptance_threshold:
                accepted.append(draft_token.token_id)
            else:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                if self.config.early_exit_on_reject:
                    break
            
            current_prompt.append(draft_token.token_id)
        
        return AcceptanceResult(
            accepted_tokens=accepted,
            rejected_tokens=rejected,
            rejection_position=rejection_position,
            accepted_length=len(accepted),
            target_probabilities=target_probs,
        )
    
    def _check_adaptive(
        self,
        prompt_tokens: List[int],
        draft_sequence: CandidateSequence
    ) -> AcceptanceResult:
        """Check using adaptive strategy."""
        # Start with strict threshold, relax if many rejections
        base_threshold = self.config.acceptance_threshold
        threshold = base_threshold
        
        if not draft_sequence.tokens:
            return AcceptanceResult(
                accepted_tokens=[],
                rejected_tokens=[],
                rejection_position=-1,
                accepted_length=0,
            )
        
        accepted: List[int] = []
        rejected: List[int] = []
        target_probs: List[float] = []
        rejection_position = -1
        
        current_prompt = list(prompt_tokens)
        
        for i, draft_token in enumerate(draft_sequence.tokens):
            # Get target probabilities
            target_candidates = self.target_model.generate_candidates(
                current_prompt,
                num_candidates=1,
                temperature=0.0,
                top_p=1.0,
            )
            
            if not target_candidates:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                threshold = base_threshold * 0.9  # Relax threshold
                break
            
            target_top = target_candidates[0]
            target_prob = target_top.probability
            target_probs.append(target_prob)
            
            # Adaptive check
            if target_prob >= threshold:
                accepted.append(draft_token.token_id)
                threshold = min(threshold * 1.05, 1.0)  # Slightly increase
            else:
                rejected.append(draft_token.token_id)
                if rejection_position == -1:
                    rejection_position = i
                threshold = max(threshold * 0.9, 0.1)  # Relax threshold
                if self.config.early_exit_on_reject:
                    break
            
            current_prompt.append(draft_token.token_id)
        
        return AcceptanceResult(
            accepted_tokens=accepted,
            rejected_tokens=rejected,
            rejection_position=rejection_position,
            accepted_length=len(accepted),
            target_probabilities=target_probs,
        )
    
    def _draft_model_get_probs(
        self,
        prompt_tokens: List[int],
        token_id: int
    ) -> float:
        """Get probability from draft model for a token."""
        # Placeholder - in real implementation would call draft model
        return 0.5


class DraftModelManager:
    """
    Manages draft model lifecycle and switching.
    
    Handles:
    - Model loading and initialization
    - Resource allocation
    - Memory management
    - Model switching
    """
    
    def __init__(self, config: SpeculativeConfig) -> None:
        """
        Initialize draft model manager.
        
        Args:
            config: Speculative decoding configuration
        """
        self.config = config
        self._target_model: Optional[DraftModel] = None
        self._draft_model: Optional[DraftModel] = None
        self._stats = DraftModelStats()
        self._is_initialized = False
    
    def initialize(self) -> None:
        """Initialize both draft and target models."""
        self._target_model = self._load_target_model()
        self._draft_model = self._load_draft_model()
        self._is_initialized = True
    
    def _load_target_model(self) -> DraftModel:
        """Load target model."""
        # Placeholder - would load actual model
        return MockDraftModel(
            self.config.target_model_name,
            vocab_size=50257,
            max_length=1024
        )
    
    def _load_draft_model(self) -> DraftModel:
        """Load draft model."""
        # Placeholder - would load actual model
        return MockDraftModel(
            self.config.draft_model_name,
            vocab_size=50257,
            max_length=1024
        )
    
    def get_target_model(self) -> Optional[DraftModel]:
        """Get target model instance."""
        return self._target_model
    
    def get_draft_model(self) -> Optional[DraftModel]:
        """Get draft model instance."""
        return self._draft_model
    
    def speculative_decode(
        self,
        prompt_tokens: List[int]
    ) -> Tuple[List[int], AcceptanceResult]:
        """
        Perform speculative decoding.
        
        Args:
            prompt_tokens: Input token IDs
        
        Returns:
            Tuple of (accepted_tokens, acceptance_result)
        """
        if not self._is_initialized:
            self.initialize()
        
        if self._draft_model is None or self._target_model is None:
            raise RuntimeError("Models not initialized")
        
        # Generate draft candidates
        generator = CandidateGenerator(self._draft_model, self.config)
        draft_sequence = generator.generate(prompt_tokens)
        
        # Verify with target model
        checker = AcceptanceChecker(self._target_model, self.config)
        result = checker.check(prompt_tokens, draft_sequence)
        
        # Update statistics
        self._update_stats(result)
        
        return result.accepted_tokens, result
    
    def _update_stats(self, result: AcceptanceResult) -> None:
        """Update performance statistics."""
        self._stats.total_speculations += 1
        self._stats.total_accepted += result.accepted_length
        self._stats.total_rejected += len(result.rejected_tokens)
        
        # Calculate running averages
        total = self._stats.total_speculations
        if total > 0:
            self._stats.avg_acceptance_ratio = (
                self._stats.total_accepted /
                max(self._stats.total_accepted + self._stats.total_rejected, 1)
            )
            
            # Estimate speedup (rough approximation)
            if self._stats.avg_acceptance_ratio > 0:
                self._stats.speedup_ratio = (
                    1 / (1 - self._stats.avg_acceptance_ratio)
                )
        
        self._stats.last_updated = time.time()
    
    def get_stats(self) -> DraftModelStats:
        """Get performance statistics."""
        return self._stats
    
    def reset_stats(self) -> None:
        """Reset performance statistics."""
        self._stats = DraftModelStats()
    
    def is_initialized(self) -> bool:
        """Check if models are initialized."""
        return self._is_initialized
    
    def cleanup(self) -> None:
        """Cleanup model resources."""
        self._draft_model = None
        self._target_model = None
        self._is_initialized = False


class MockDraftModel(DraftModel):
    """
    Mock draft model for testing and development.
    
    Generates synthetic token probabilities.
    """
    
    def __init__(
        self,
        model_name: str,
        vocab_size: int = 50257,
        max_length: int = 1024
    ) -> None:
        """Initialize mock draft model."""
        self.model_name = model_name
        self._vocab_size = vocab_size
        self._max_length = max_length
        self._call_count = 0
    
    def generate_candidates(
        self,
        prompt_tokens: List[int],
        num_candidates: int,
        temperature: float = 1.0,
        top_p: float = 0.9
    ) -> List[CandidateToken]:
        """Generate mock candidates."""
        import random
        
        self._call_count += 1
        candidates = []
        
        for i in range(num_candidates):
            token_id = random.randint(1, self._vocab_size - 1)
            probability = random.uniform(0.1, 0.9)
            log_prob = -abs(probability)
            
            candidate = CandidateToken(
                token_id=token_id,
                text=f"<token_{token_id}>",
                probability=probability,
                log_probability=log_prob,
                position=i,
            )
            candidates.append(candidate)
        
        # Sort by probability
        candidates.sort(key=lambda c: c.probability, reverse=True)
        
        # Update ranks
        for i, c in enumerate(candidates):
            c.rank = i
        
        return candidates
    
    def get_token_probabilities(
        self,
        prompt_tokens: List[int],
        candidate_tokens: List[int]
    ) -> List[float]:
        """Get mock probabilities."""
        import random
        return [random.uniform(0.1, 0.9) for _ in candidate_tokens]
    
    def get_vocab_size(self) -> int:
        """Get vocabulary size."""
        return self._vocab_size
    
    def get_max_length(self) -> int:
        """Get maximum length."""
        return self._max_length
    
    def get_model_name(self) -> str:
        """Get model name."""
        return self.model_name


def create_speculative_config(
    draft_model: str = "gpt2-small",
    target_model: str = "gpt2-medium",
    num_draft_tokens: int = 4,
    strategy: AcceptanceStrategy = AcceptanceStrategy.EXACT_MATCH
) -> SpeculativeConfig:
    """
    Create a speculative decoding configuration.
    
    Args:
        draft_model: Name of draft model
        target_model: Name of target model
        num_draft_tokens: Number of tokens to speculate
        strategy: Acceptance strategy
    
    Returns:
        SpeculativeConfig instance
    """
    return SpeculativeConfig(
        draft_model_name=draft_model,
        target_model_name=target_model,
        num_draft_tokens=num_draft_tokens,
        acceptance_strategy=strategy,
    )


def create_aggressive_config() -> SpeculativeConfig:
    """
    Create aggressive speculative decoding config.
    
    More draft tokens, lower acceptance threshold.
    """
    return SpeculativeConfig(
        num_draft_tokens=8,
        acceptance_threshold=0.5,
        early_exit_on_reject=False,
        use_adaptive_drafting=True,
    )


def create_conservative_config() -> SpeculativeConfig:
    """
    Create conservative speculative decoding config.
    
    Fewer draft tokens, higher acceptance threshold.
    """
    return SpeculativeConfig(
        num_draft_tokens=2,
        acceptance_threshold=0.9,
        early_exit_on_reject=True,
        use_adaptive_drafting=False,
    )
